spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.0
  output:
    ansi:
      enabled: always
  application:
    name: reservation-service
  data:
    mongodb:
      database: Reservation
      port: 27017
      host: 192.168.223.250
      password: example
      username: root
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

server:
  port: 8085
reactive:
  feign:
    logger:
      enabled: true

