version: '3'
services:
  mongo:
    image: mongo
    restart: always
    command: --config /etc/mongo/mongod.conf
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_conf:/etc/mongo/